version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: magic-royale-db
    restart: always
    environment:
      POSTGRES_USER: magic_user
      POSTGRES_PASSWORD: magic_password
      POSTGRES_DB: magic_royale
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
